# Generated by Django 4.1.1 on 2022-09-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HighImpactExperiences',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('RTX_name', models.CharField(max_length=50)),
                ('Freshman_desc', models.CharField(max_length=200)),
                ('Sophomore_desc', models.CharField(max_length=200)),
                ('Junior_desc', models.CharField(max_length=200)),
                ('Senior_desc', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Minors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=4)),
                ('suffix', models.CharField(max_length=4)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CRN', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc_text', models.CharField(max_length=200)),
                ('course_num', models.IntegerField(default=0)),
                ('credit_hours', models.IntegerField()),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.faculty')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.departments')),
            ],
        ),
    ]
