# Generated by Django 4.1.1 on 2022-09-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.majors')),
                ('minor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.minors')),
            ],
        ),
    ]
